# Generated by Django 2.1 on 2020-07-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_league_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='string',
            field=models.CharField(choices=[('ms1', 'MS1'), ('msx', 'MSX'), ('ms2', 'MS2'), ('cs1-x', 'CS1-X'), ('cs1-2', 'CS1-2'), ('csx-2', 'CSX-2'), ('iy1', 'IY1'), ('iyx', 'IYX'), ('iy2', 'IY2'), ('2y1', '2Y1'), ('2yx', '2YX'), ('2y2', '2Y2'), ('au1,5-alt', 'AU1,5-ALT'), ('au1,5-ust', 'AU1,5-UST'), ('au2,5-alt', 'AU2,5-ALT'), ('au2,5-ust', 'AU2,5-UST'), ('au3,5-alt', 'AU3,5-ALT'), ('au3,5-ust', 'AU3,5-UST'), ('iyau1,5-alt', 'IYAU1,5-ALT'), ('iyau1,5-ust', 'IYAU1,5-UST'), ('tg0-1', 'TG0-1'), ('tg2-3', 'TG2-3'), ('tg4-6', 'TG4-6'), ('tg7+', 'TG7+'), ('h1', 'H1'), ('hx', 'HX'), ('h2', 'H2'), ('kgvar', 'KGVAR'), ('kgyok', 'KGYOK'), ('tctek', 'TCTEK'), ('tccift', 'TCCIFT'), ('iyms1/1', 'IYMS1/1'), ('iyms1/x', 'IYMS1/X'), ('iyms1/2', 'IYMS1/2'), ('iymsx/x', 'IYMSX/X'), ('iymsx/1', 'IYMSX/1'), ('iymsx/2', 'IYMSX/2'), ('iyms2/2', 'IYMS2/2'), ('iyms2/x', 'IYMS2/X'), ('iyms2/1', 'IYMS2/1')], max_length=20),
        ),
    ]
